### ISSUE TITLE
Error e.content.blocks.map is not a function after upgraded Laravel 6 to 8 and Twill 2.0 to 2.5

### ISSUE THREAD

**Issue by pietrantonio91** [area17/twill#1260]
## Description

I upgraded my Laravel from v6 to v8 and Twill from 2.0.1 to 2.5.2 and now I cannot update my models. In browser console I see this error when I press "Save" button:

> TypeError: e.content.blocks.map is not a function

### Steps to reproduce

Upgrade from Laravel v6 to Laravel v8.42.1 following official docs guide.
Upgrade Twill form 2.0.1 to 2.5.2.
Try to save a Model.

### Expected result

I expect the model updates on DB.

### Actual result

> TypeError: e.content.blocks.map is not a function
>     at v (chunk-common.443541eb.js:1)
>     at g.<anonymous> (chunk-common.443541eb.js:1)
>     at Array.<anonymous> (chunk-vendors.40cddcf5.js:7)
>     at g.dispatch (chunk-vendors.40cddcf5.js:7)
>     at g.dispatch (chunk-vendors.40cddcf5.js:7)
>     at Cr.<anonymous> (main-form.005ad1eb.js:1)
>     at Array.<anonymous> (chunk-vendors.40cddcf5.js:20)
>     at dt (chunk-vendors.40cddcf5.js:20)

### Versions

Twill: v2.5.2
Laravel: v8.42.1
Php: v7.4.26
DB Engine: MySQL

**Comment by pboivin** [comment]
Hi @pietrantonio91, 
If you have a custom build of the Twill assets (ie. `php artisan twill:build`), make sure to rebuild after running `composer update`. If you're running on the default assets, you can run `php artisan twill:update` to publish the new ones.

**Comment by pietrantonio91** [comment]
Hi @pboivin,
thank you so much for your help.
The command `php artisan twill:update` did the trick for me (I didn't know twill:update command)
